### ISSUE TITLE
PcscReader disconnection mode documentation

### ISSUE THREAD

**Issue by amessara-billettiqueservices** [eclipse/keyple-plugin-pcsc-java-lib#11]
Hello team,
The PcscReader disconnection mode does not reflect correctly the default value.
It has been changed to `RESET` but the documentation still says `LEAVE`
https://github.com/eclipse/keyple-plugin-pcsc-java-lib/blob/9333e58a4b18e9ca391db188ba7ec75cf536cbdf/src/main/java/org/eclipse/keyple/plugin/pcsc/PcscReader.java#L183-L196
https://github.com/eclipse/keyple-plugin-pcsc-java-lib/blob/9333e58a4b18e9ca391db188ba7ec75cf536cbdf/src/main/java/org/eclipse/keyple/plugin/pcsc/AbstractPcscReaderAdapter.java#L380-L386
https://github.com/eclipse/keyple-plugin-pcsc-java-lib/blob/9333e58a4b18e9ca391db188ba7ec75cf536cbdf/src/main/java/org/eclipse/keyple/plugin/pcsc/AbstractPcscReaderAdapter.java#L54

**Comment by jeanpierrefortune** [comment]
Hi Aghilas,

The documentation has been corrected in the main branch and will be included in the next release.

Best regards
